### ISSUE TITLE
A response for step 6 is skipped

### ISSUE THREAD

**Issue by IshanaRaina** [githubtraining/continuous-delivery#11]
**Current behavior**

The main course page lists **Approve pull request** as **Step 6** (highlighted in screenshot)

![](https://i.imgur.com/pHwEiiJ.png)

Whereas in the course content, **Approve the pull request** has been erroneously numbered as **Step 7**. Due to this, the numbering of the steps in the course content are ahead of the main course page by 1, starting with **Step 7: Approve the pull request**.

![](https://i.imgur.com/GjccmyU.png)

**Solution**

Change step numbers 7, 8, 9, 10, 11, 12 in the course content to step numbers 6, 7, 8, 9, 10, 11 respectively so that they match the main course page.

**Comment by hectorsector** [comment]
Thanks for the report, @IshanaRaina!

If you'd like to attempt to fix this, the relevant files are in the [`responses/` folder](https://github.com/githubtraining/continuous-delivery/tree/master/responses), starting with [`responses/07_approve.md`](https://github.com/githubtraining/continuous-delivery/blob/master/responses/07_approve.md).

**Comment by IshanaRaina** [comment]
Hey @hectorsector, 2 things came up:

1. The [Contributing Guide](https://github.com/githubtraining/community-contributors/blob/master/CONTRIBUTING.md) mentions forking both the course as well as the template repository. But the **template repository** link on the [README.md](https://github.com/githubtraining/continuous-delivery) throws a 404 error. In light of that, I wasn't able to follow the Contributing Guide line by line and instead forked just this repo, updated the step numbers and opened PR #17. 

2. While perusing through the [responses](https://github.com/githubtraining/continuous-delivery/tree/master/responses) 📁, I made yet another observation. When I take the course, the [06_env-variables.md](https://github.com/githubtraining/continuous-delivery/blob/master/responses/06_env-variables.md) file doesn't show up. The course jumps from Step 5 directly to Step 7 as seen 👇 which is what caused me to open this issue in the first place!
![](https://i.imgur.com/VaDAnKw.png)

So looking at the flow of steps in the **responses** 📁, **Step 5: Confirm AWS S3 configuration** is followed by **Step 6: Create and store environment variables** which is followed by **Step 7: Approve the pull request** so maybe in that case we don't want to update the step numbers at all but instead update the code files to trigger the file that was skipped 🤷‍♀

**Comment by hectorsector** [comment]
This was fixed in #17. Thanks @IshanaRaina :octocat:
