### ISSUE TITLE
nodejs8.10 deprecated for AWS Lambda

### ISSUE THREAD

**Issue by janerikcarlsen** [githubtraining/continuous-delivery#25]
Since Feb 3, `nodejs8.10` has been deprecated for AWS Lambda. 

On the initial Staging deployment, deploying to AWS failed for me: 
`CREATE_FAILED            AWS::Lambda::Function    MainFunction             The runtime parameter  
                                                                           of nodejs8.10 is no    
                                                                           longer supported for   
                                                                           creating or updating   
                                                                           AWS Lambda functions.  
                                                                           We recommend you use   
                                                                           the new runtime        
                                                                           (nodejs12.x) while     
                                                                           creating or updating   
                                                                           functions. (Service:   
                                                                           AWSLambdaInternal;     
                                                                           Status Code: 400;      
                                                                           Error Code: InvalidPar 
                                                                           ameterValueException;`

I changed the node version to `nodejs12.x` and staging workflow passed. However for the production flow `nodejs12.x` failed with: 
```
Run docker://admiralawkbar/aws-nodejs:latest
...
...
Building resource 'MainFunction'
Error: 'nodejs12.x' runtime is not supported
ERROR! Failed to build SAM application!
```

Fix suggestion: Update node version to either `nodejs10.x` OR update both node version to `nodejs12.x` and deployment mechanism for production workflow to using `github/deploy-nodejs@master`

**Comment by janerikcarlsen** [comment]
Failing run due to `nodejs8.10` not supported: https://github.com/janerikcarlsen/github-actions-continuous-delivery/runs/489917975?check_suite_focus=true
Failing run due to `nodejs12.x` failing for `docker://admiralawkbar/aws-nodejs:latest`: https://github.com/janerikcarlsen/github-actions-continuous-delivery/runs/489960153?check_suite_focus=true
Successful run with `nodejs12.x` and using `github/deploy-nodejs@master` for production workflow: https://github.com/janerikcarlsen/github-actions-continuous-delivery/runs/490018726?check_suite_focus=true

**Comment by hectorsector** [comment]
Thanks for the report @janerikcarlsen ❤️ I was able to confirm that this course is blocked because of this.

```
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal)
```

/cc @admiralawkbar who wrote the action, @mattdavis0351 who designed most of this course
