### ISSUE TITLE
Issue with Node 8.x and failing builds

### ISSUE THREAD

**Issue by kellyarwine** [githubtraining/continuous-delivery#31]
For the Course maintenance swarm event, I attempted to take this course to replicate two issues that had been reported.  While taking the course, I found the following issue:

* There's an issue with Node CI, version 8.x.  I ran into it on Step 4.

![image](https://user-images.githubusercontent.com/2262535/89049811-6b87ec80-d317-11ea-86fa-6d7043d9e023.png)

**Comment by hectorsector** [comment]
Think this was fixed in https://github.com/githubtraining/continuous-delivery-aws/issues/25
