### ISSUE TITLE
Stuck at step 6

### ISSUE THREAD

**Issue by ryanditjia** [githubtraining/continuous-delivery#35]
Hello, first of all I want to say that I’m loving these tutorials.

I’ve gotten stuck at step 6 twice now. After approving the PR, the bot merges, but no response after.

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/16177372/94369509-4eec1300-0114-11eb-90b8-1117e2db0cff.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/16177372/94369511-56abb780-0114-11eb-9e88-aa35fcbc5daa.png">

**Comment by davenowell** [comment]
Hi @ryanditjia.  We have triggered the bot so that you can move on to the next step.  If you would like to make your repo public, we can troubleshoot further.  But, you should be able to continue now.

**Comment by davenowell** [comment]
@ryanditjia - A bit more information. There are two things that you will need to do manually: 

- merge master into the `staging-test `branch
- Then open a PR with base `master` and head `staging-test`

From inside this new PR, follow the instructions found at https://github.com/githubtraining/continuous-delivery-aws/blob/master/responses/08_test.md. 

I'll print them here for your convenience:

____________

# Testing the workflow

Now that the proper configuration and workflow files are present, let's test this action out!

## Step 7: Test the staging action

In this pull request, there's a small change to the game. Once you add the label, you should be able to see the deployment!

### :keyboard: Activity: Add the proper label to this pull request

1. On the right hand side, click **Labels** or the gear next to it
2. Select the label titled **stage**

**Comment by ryanditjia** [comment]
Hello Dave, thanks for the help, I’m able to trigger the next step.
