### ISSUE TITLE
Broken ‘Get help’ link on the sidebar

### ISSUE THREAD

**Issue by ryanditjia** [githubtraining/continuous-delivery#36]
This link appears to be broken: https://github.community/t5/GitHub-Learning-Lab/bd-p/learn.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/16177372/94369645-53fd9200-0115-11eb-9b92-83bc5137b617.png">

**Comment by hectorsector** [comment]
This course is no longer publicly available, but I've also confirmed this link is no longer broken!
