### ISSUE TITLE
BUG: Course blocked at step 6/7

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/continuous-delivery#37]
A bug has been reported in Halp and in the [Community forum](https://github.community/t/im-cant-advance-in-this-lab-github-actions-github-actions-continuous-delivery-with-aws/139706/3), stating that the course is blocked after step 6/7. 

Examples: 
- https://github.com/Swaraj2904/github-actions-continuous-delivery/pull/2
- https://github.com/bsa-coder/github-actions-continuous-delivery/pull/2
- https://github.com/andpberr/github-actions-continuous-delivery/pull/2

It appears the user [approves the PR](https://github.com/githubtraining/continuous-delivery-aws/blob/3570213f6b26f7061bc9509c00e2e2ec8be68698/config.yml#L181), the [bot merges](https://github.com/githubtraining/continuous-delivery-aws/blob/3570213f6b26f7061bc9509c00e2e2ec8be68698/config.yml#L200), but then the course freezes. 

One user also reported a merge conflict in this PR, but that doesn't seem consistent across all bugs.

cc @ps-programs @mattdavis0351 👀

**Comment by brianamarie** [comment]
In case anyone is curious and would like to help troubleshoot, we will likely go through the course using a tool called [smee.io](https://smee.io/) to trace the signals sending webhooks (from GitHub) that the bot is listening to (Learning Lab). We'll especially look for any unexpected behavior around [the steps where the course is freezing](https://github.com/githubtraining/continuous-delivery-aws/blob/3570213f6b26f7061bc9509c00e2e2ec8be68698/config.yml#L200).

**Comment by hcientist** [comment]
So I just started this tonight and am stuck at the same place. I am not sure why, but [my `node-forge` version expected by `selfsigned` started as `0.8.2`](https://github.com/hcientist/github-actions-continuous-delivery/blob/4a5a79eb32b91f4f666a4d26a30ce87a4755a59c/package-lock.json#L7443), but then whenever i merge branches (e.g. [[1](https://github.com/hcientist/github-actions-continuous-delivery/commit/4101b5fc6cf77d573614846f78c43f2abb37a1eb#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R7537)], [[2](https://github.com/hcientist/github-actions-continuous-delivery/commit/edae8541b648137365c73d3b98ff0ea82b3bbfbe#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R7537)]), i have to resolve a conflict of bumping it to `0.9.0`. Probably [this merge](https://github.com/githubtraining/continuous-delivery-aws/blob/master/config.yml#L200) is failing, but I'm unsure how to proceed /-: I have tried merging master to `staging-test`, sresolving the conflict, and pushing back to `staging-test`, but that was not sufficient for the [lab(?)](https://lab.github.com/githubtraining/github-actions:-continuous-delivery-with-aws) to proceed.

**Comment by hcientist** [comment]
omg, i was trying to fix it by updating the package versions in package* on master prior to doing the rest of the lab... i deleted my first attempt 🤦‍♂️ breaking all the links above 🤦‍♂️

**Comment by brianamarie** [comment]
Thank you for your work on this, @hcientist! Out of curiosity, did you have smee.io enabled while you were testing? I wonder if that would give us any more insight 🤔

**Comment by hcientist** [comment]
Unfortunately not. I can try to make time some time this week.

**Comment by hcientist** [comment]
aight so lemme [figure out smee](https://lab.github.com/githubtraining/getting-started-with-github-apps)

**Comment by brianamarie** [comment]
@hcientist It may not be helpful, but at about minute 40 of [this youtube video](https://www.youtube.com/watch?v=nQ5oh9Et1As), I walk through configuring smee.io in a Learning Lab course for debugging.

**Comment by hcientist** [comment]
https://youtu.be/nQ5oh9Et1As?t=2321 😃 here we go

**Comment by hcientist** [comment]
What happens if I paste this smee log?
```
delete                less than a minute ago
push                  less than a minute ago
check_suite           1 minute ago
check_run             1 minute ago
pull_request          1 minute ago
label                 1 minute ago
check_run             2 minutes ago
pull_request          2 minutes ago
push                  2 minutes ago
pull_request_review   2 minutes ago
pull_request          6 minutes ago
issue_comment         6 minutes ago
pull_request          6 minutes ago
push                  6 minutes ago
push                  11 minutes ago
delete                11 minutes ago
issue_comment         11 minutes ago
pull_request          11 minutes ago
push                  11 minutes ago
pull_request          11 minutes ago
check_suite           12 minutes ago
check_run             12 minutes ago
check_run             12 minutes ago
check_run             12 minutes ago
check_run             12 minutes ago
check_run             13 minutes ago
check_run             13 minutes ago
check_run             13 minutes ago
check_run             13 minutes ago
check_run             13 minutes ago
check_run             13 minutes ago
pull_request          13 minutes ago
push                  13 minutes ago
check_suite           17 minutes ago
check_run             17 minutes ago
check_run             17 minutes ago
check_run             17 minutes ago
check_run             17 minutes ago
check_run             17 minutes ago
check_run             18 minutes ago
check_run             18 minutes ago
check_run             18 minutes ago
check_run             18 minutes ago
check_run             18 minutes ago
issue_comment         18 minutes ago
check_run             18 minutes ago
pull_request          18 minutes ago
push                  18 minutes ago
check_suite           31 minutes ago
check_run             31 minutes ago
check_suite           31 minutes ago
check_run             31 minutes ago
check_run             31 minutes ago
check_run             31 minutes ago
check_run             31 minutes ago
check_run             31 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             32 minutes ago
check_run             33 minutes ago
check_run             33 minutes ago
check_run             33 minutes ago
check_run             33 minutes ago
check_run             33 minutes ago
issue_comment         33 minutes ago
check_run             33 minutes ago
check_suite           33 minutes ago
pull_request          33 minutes ago
push                  33 minutes ago
check_run             34 minutes ago
issue_comment         34 minutes ago
check_suite           34 minutes ago
pull_request          34 minutes ago
push                  34 minutes ago
ping                  about 1 hour ago
```

I'm not entirely sure what this tells me ¯\\_(ツ)_/¯ Still [stopped at same step](https://github.com/hcientist/github-actions-continuous-delivery)
