### ISSUE TITLE
New course banner does not go away or update

### ISSUE THREAD

**Issue by bdougie** [githubtraining/continuous-delivery#7]
## description

I start testing this course and noticed right away that there is a new version right when I started. when clicking the `Renew you registration` button, it refreshes but does nothing to the original repo. 

![Screenshot 2019-11-07 13 26 57](https://user-images.githubusercontent.com/5713670/68429163-7041ba80-0162-11ea-928e-f0e110300fc7.png)

Curious if anyone else is seeing this. 

## steps to reproduce
1. Sign for the course from the https://lab.github.com/githubtraining/continuous-delivery-with-github-actions link.
2. Click the renew button
3. Note nothing changes and banner remains

**Comment by hectorsector** [comment]
Hm... I haven't been able to replicate this, @bdougie, but I do know we renamed this course. Perhaps it has to do with that. Is it still happening?

**Comment by bdougie** [comment]
Just checked and it seems, to be fine now. I also see the name change took effect.
